Update AMD64 support for SEV Memory Encryption
intel-go/cpuid pull request #18
Opened 2021-04-09 13:44 UTC by jimcadden

Signed-off-by: Jim Cadden <jcadden@ibm.com>

2021-05-11 19:11 UTC, jimcadden commented
/test

2021-05-13 20:47 UTC, jimcadden commented
@aregm would you please assign a reviewer for this PR?

2021-05-24 16:18 UTC, jimcadden commented
@aregm would you please proceed with your review? This PR is a prerequisite for a larger set of changes already approved for upstream in the Kata Containers project. I appreciate your help & feedback.

2021-06-01 17:14 UTC, aregm requested changes

2021-06-01 19:13 UTC, jimcadden commented on cpuid.go
> +type MemoryEncryptionCapabilities struct {
@aregm I think renaming these to be AMD-specific (i.e., `AMDMemoryEncryptionCapabilites`) is best given that a number of the elements are SEV-specific and seem unlikely to be shared across MKTME or any other encryption technology (e.g., `CBitPosition`, `PhysAddrReduction`, `MinSevNoEsAsid`) 

cc. @sameo

2021-06-01 20:33 UTC, aregm commented on cpuid.go
> +type MemoryEncryptionCapabilities struct {
@jimcadden ok, should be enough.

2021-06-01 21:14 UTC, jimcadden commented on cpuid.go
> +func HasMemEncryptFeature(feature uint32) bool {
@aregm Its unclear to me if a generic `HasMemEncryptFeature` function is useful, or if we are better off with two sets of interfaces, one for SME/SEV and a separate one  for TME/MKTME (if one is even necessary). With SEV, we are required to pull architecture-specific values from CPUID/MSRs (e.g., `CBitPosition`) that are passed as arguments to QEMU, so an interface into CPUID is needed. I'm not sure if there's a similar requirement for MKTME that couldn't be gathered via CPU flags, or by querying the filesystem. 

I'm inclined to re-label all this as `AMDMemEncrypt` and keep the code largely as-is. 

Thoughts? 

cc. @sameo

2021-06-01 21:22 UTC, jimcadden commented on cpuid.go
> +func HasMemEncryptFeature(feature uint32) bool {
If you're curious why-in-the-world QEMU requires architecture-specific values, which the QEMU process could easily detect, to be passed im as explicit command line augments... well I asked... the answer has to do handling the migration of encrypted VMs across generations of SEV architectures.  In fact, QEMU already does automatically detect the values but only to confirm the ones you've specified are correct. (face palm)

2021-06-01 23:17 UTC, aregm commented on cpuid.go
> +func HasMemEncryptFeature(feature uint32) bool {
@jimcadden sounds good, you can keep them separate. MKTME has a somewhat similar but different in essence approach (https://software.intel.com/content/dam/develop/external/us/en/documents-tps/multi-key-total-memory-encryption-spec.pdf). So, theoretically it is possible to combine under a unified interface and then specialize under the implementation, but it would be overkill. I would prefer to keep it simple under hasFeature(...) and branch. So, no objections.

2021-06-02 15:52 UTC, jimcadden commented on cpuid_amd64.go
> +func leaf0x8000001f() {
Done

2021-06-02 15:54 UTC, jimcadden commented on cpuid.go
> +	FSGSBASE:              "FSGSBASE",
Hm.. this space change happened automatically. Must be `go-vim`

2021-06-02 15:55 UTC, jimcadden commented
Thanks for the review @aregm. I've made the interfaces explicit for AMD only. Let me know if this will work.

2021-06-02 15:56 UTC, aregm approved these changes

2021-06-02 15:56 UTC, merged